# Generated by Django 4.0.4 on 2022-06-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
